name: Publish Python Package with Poetry and uv

on:
  push:
    branches:
      - main # Trigger for TestPyPI
  release:
    types: [published] # Trigger for production PyPI

jobs:
  publish:
    environment: ${{ github.event_name == 'release' && 'pypi' || 'testpypi' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        # need full history so tags are available to the runner
        fetch-depth: 0

    - name: Install uv
      run: pip install uv

    - name: Set up Python and install Poetry
      run: |
        uv venv
        uv pip install poetry

    - name: Build package
      run: |
        source .venv/bin/activate
        poetry install --with ci
        poetry build

    - name: Publish to TestPyPI
      if: github.event_name != 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

    - name: Publish to PyPI
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
